### ISSUE TITLE
Pre-launch checklist

### ISSUE THREAD

**Issue by bludnic** [bludnic/opentrader#20]
## Documentation

- [x] Project has a LICENSE file with an open source license
- [x] Project has basic documentation (README, CONTRIBUTING, CODE_OF_CONDUCT)
- [x] The name is easy to remember, gives some idea of what the project does, and does not conflict with an existing project or infringe on trademarks
- [x] The issue queue is up-to-date, with issues clearly organized and labeled

## Code

- [x] Project uses consistent code conventions and clear function/method/variable names
- [x] The code is clearly commented, documenting intentions and edge cases
- [x] There are no sensitive materials in the revision history, issues, or pull requests (for example, passwords or other non-public information)
