### ISSUE TITLE
Dashboard: Add favicon, logo, manifest, meta and other assets

### ISSUE THREAD

**Issue by bludnic** [bludnic/opentrader#5]
- [x] Add favicon
- [x] Replace logo in the Github organisation
- [x] Add logo in README.md
- [x] Replace logo in frontend app
